@startwbs aceengineer_resources_1

scale 2
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor Tomato


title VA AceEngineer Resources \n KVM Switch Analysis

* Work Computers

** Work 1 - Doris Laptop
*** Software: VS Code, OpenFoam, Blender, FreeCAD
*** Primary: Doris Work
*** Can Remote to ACMA

** Ace Desktop Windows 1
*** Display: Monitor
*** Primary: ACMA Work
*** Software: VS Code, OpenFoam, Blender, FreeCAD

** Ace Desktop Windows 2
*** Display: Monitor
*** Primary: OrcaFlex Analysis

** Ace Desktop Linux
*** Display: Monitor
*** Primary: File server, Misc. software
*** Software: VS Code, OpenFoam, Blender, FreeCAD
*** Server: Files

footer
%date("yyyy.MM.dd' at 'HH:mm")
%filename()
end footer

@endwbs
