@startuml server_remote_desktop

scale 2
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor Tomato


title Server \n Understanding Remote Desktop

package "Server Resources" {
    component "**CPU \nNc Cores \nNp Processors**" as CPU
    component "Memory\nDisk" as Memory
    component "Software License i.e. OrcaFlex" as Software
    component "**Data**" as Data
}

package "User 1" as user1 {
    agent "Run OrcaFlex Dynamics \nUsing Np Processors" as CPU_user1
    agent "Memory\nDisk" as Memory_user1
    agent "Software License i.e. OrcaFlex" as Software_user1
    agent "**Data**" as Data_user1
}

note right

    Notes:
        All resources for 1 user
end note

CPU --> CPU_user1
Memory --> Memory_user1
Software --> Software_user1
Data --> Data_user1

package "2 Users" as 2user {
    agent "Run OrcaFlex Dynamics \nUsing Np Processors" as CPU_user2
    agent "Memory\nDisk" as Memory_user2
    agent "Software License i.e. OrcaFlex" as Software_user2
    agent "**Data**" as Data_user2
}

note right

    Notes:
        1a/ Resources (RAM, CPU, Drive, etc) shared. 
          - Able to run Np processors again but will slow down the machine. 
        1b/ Additional license to Run software (ANSYS/OrcaFlex etc.) with additional license by user
        1c/ Able to access the shared data 
end note

user1 --> 2user
CPU_user1 --> CPU_user2
Memory_user1 --> Memory_user2
Software_user1 --> Software_user2
Data_user1 --> Data_user2

note Bottom

    Notes:
        For 2 users, It is important to close all licensed software 
        and log-out in the following example scenarios: 
        1/ When user licensed software runs are done (even after a day or Monday)
        2/ When user licensed software is going to be unused for more than 1 hour duration
        3/ Should not keep open to just block/hoard license unless there is an urgency.

        **Best solution** : Shared username (eg: orcaflex, ansys etc.)/password pair to login and logout.
           **Full Transperency and Trust** and **No confidentiality** 
        Example solution providers:
        - tightVPN (free)
        - splashtop (USD 10/mo/user)
        - TeamViewer (USD 25/mo for 3 devices), etc.
end note


footer
%date("yyyy.MM.dd' at 'HH:mm")
%filename()
end footer

@enduml