@startuml viz_architecture
scale 3
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor Tomato

title Visualization \nArchitecture

start

    note right
        Objective: Visualization Architecture:
         - 
    end note

    partition "Data: " {

        :.yml;
            note right
            Pros:
            - easy difinition
            Cons:
            - difficult for complex data 
            end note

        :.csv;
            note right
             directly from multiple data sources
             able to define a more clean data
             able to metadata as required to filter and plot
             - can metadata be added directly to CSV coming from the data source?
            end note

        :.xlsx (Not **Supported**);
            note right
             onerous requirements for:
             - data clean
             - data transformation 
            end note
    }

    partition "Transform: " {
        :filter - df column value;
            note right
            able to filter data by column value
            end note
        :filter - df column value contains;
            note right
            **To be Implemented**
            able to filter data by column value contains
            end note
        :sort - df column;
            note right
            **To be Implemented**
            end note
    }

    partition "plot: labels" {
        :Group labels;
            note right
            Mainly for making plot legend unique
            Used for: 
            - Legend labels
            end note
    }

    partition "plot: legend" {
        :legend;
            note right
            Used for:
            - plot legends
            Autogenerated using:
            - group label
            - x column or y column 
            end note
    }

    partition "plot: line-color" {
        :line-color;
            note right
            Used for:
            - line color
            - marker color
            - marker color
            Autogenerated using:
            - color function
            - Based on number of groups
            end note
    }
    partition "plot: line-style" {
        :line-style;
            note right
            Used for:
            - line style
            Autogenerated using:
            - line style function
            - Based on number of groups
            end note
    }
    partition "plot: alpha" {
        :line-style;
            note right
            Used for:
            - line style
            Transperency autogenerated using:
            - function
            - Based on number of groups
            end note
    }

stop

footer
%date("yyyy.MM.dd' at 'HH:mm")
%filename()
end footer

@enduml
