# Third party imports

from test_df_basic_statistics import test_run_process as test_df_basic_statistics_copy
from test_df_basic_statistics_add_to_df import test_run_process as test_df_basic_statistics_add_to_df_copy  

test_df_basic_statistics_copy()
test_df_basic_statistics_add_to_df_copy()


